### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by aaronwi** [flathub/com.tdameritrade.ThinkOrSwim#1]
System info:
java --version
openjdk 11.0.13 2021-10-19
OpenJDK Runtime Environment 18.9 (build 11.0.13+8)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode, sharing)

uname -r
5.15.12-200.fc35.x86_64

uname -a
Linux fedora 5.15.12-200.fc35.x86_64

Issue
Random slowdowns or random crashes relating to Zero window size

Reproduce
flatpak run com.tdameritrade.thinkorswim

Error in terminal:

JDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.devexperts.jnlp.JavaLibraryPathUpdater (file:/home/$user$/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/suit/1972.1.9/tos-suit-1972.1.9.jar) to field java.lang.ClassLoader.usr_paths
WARNING: Please consider reporting this to the maintainers of com.devexperts.jnlp.JavaLibraryPathUpdater
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by jkoelker** [comment]
It is not, just no one has reproduced the issue. I use this on a daily basis on Arch, and I know of a few other Fedora and Ubuntu users.

**Comment by jkoelker** [comment]
I've restored the original content, if this is still an issue go ahead and reopen it. If you have time to track down the issue, pull requests are most welcome.
