### ISSUE TITLE
Won't Launch on Ubuntu 20.04.4

### ISSUE THREAD

**Issue by jmac09** [flathub/com.tdameritrade.ThinkOrSwim#4]
When trying to install ThinkOrSwim using flatpak on Ubuntu 20.04.4 LTS (Focal Fossa).

Starting Installer ...
The installation directory has been set to /home/[my user name]/thinkorswim.
Extracting files ...
Finishing installation ...
sed: can't read /home/[my user name]/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/workspace.*.tos.prod.xml: No such file or directory
/app/bin/thinkorswim: line 15: /home/[my user name]/.var/app/com.tdameritrade.ThinkOrSwim/data/thinkorswim/thinkorswim: No such file or directory

Clicking in TOS icon to launch the program does nothing, and when running flatpak run com.tdameritrade.ThinkOrSwim I get the same error as mentioned above.

Please fix the issue. Thanks!

**Comment by jkoelker** [comment]
This is the same issue as #3, lets keep the discussion centralized.
